backend:
  name: github
  repo: fatehaliyev/dayday
  branch: 2026-04-20-qn6c
  base_url: https://www.haliyikamamerkezi.online
  auth_endpoint: api/auth

local_backend: true

publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Bloq Yazıları"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Başlıq", name: "title", widget: "string" }
      - { label: "Tarix", name: "date", widget: "datetime" }
      - { label: "Şəkil", name: "thumbnail", widget: "image" }
      - { label: "Mətn", name: "body", widget: "markdown" }
